# -*- coding: utf-8 -*-
"""2_AoL 2_Deep Learning-Based Text Analysis for Mental Health Condition Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TszoFKusnYLrDaWiUsmeHAGtC8X969_n

# Data Overview, EDA, and Text Based Statistical Features

# Install and Import Library
"""

!pip install tensorflow -q
!pip install imbalanced-learn -q

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, SpatialDropout1D
from sklearn.utils import class_weight

print("TensorFlow Version :", tf.__version__)
print("GPU Available      :", len(tf.config.list_physical_devices('GPU')))

"""# Load Dataset"""

df = pd.read_csv('mental_health.csv')

"""# Exploring Data

The dataset consists of statements tagged with one of the following seven mental health statuses:

*   Normal
*   Depression
*   Suicidal
*   Anxiety
*   Stress
*   Bi-Polar
*   Personality Disorder

Personality Disorder
The data is sourced from diverse platforms including social media posts, Reddit posts, Twitter posts, and more.
"""

df.head()

df.info()

df.describe()

"""# Explatory Data Analysis"""

df = df[['statement', 'status']]
df.reset_index(drop=True, inplace = True)

df.shape
df.head()

"""Data Cleaning (Check and Remove Null Value)"""

df.isnull().sum()

df.dropna(inplace = True)
df.isnull().sum()

print(df['status'].value_counts())

"""Check Class Imbalance"""

plt.figure(figsize=(10,5))
sns.countplot(x=df['status'], order=df['status'].value_counts().index)
plt.xticks(rotation=45)
plt.title("Label Distribution")
plt.show()

df.describe()

status_counts = df['status'].value_counts()

plt.figure(figsize=(6, 6))
plt.pie(status_counts, labels=status_counts.index, autopct='%1.1f%%', startangle=140)

plt.title('Distribution of Mental Health Conditions')
plt.axis('equal')
plt.tight_layout()
plt.show()

df[df['statement']== 'what do you mean?']

"""Looking Raw Texts"""

random_statements = df.groupby('status')['statement'].apply(lambda x: x.sample(n=1).iloc[0])

for status, statement in random_statements.items():
    print(f"Status: {status}")
    print(f"Statement: {statement}\n")

"""# Text Based Statistical Features"""

df['char_count'] = df['statement'].apply(len)
df['word_count'] = df['statement'].apply(lambda x: len(x.split()))
df['unique_words'] = df['statement'].apply(lambda x: len(set(x.split())))
df['lexical_diversity'] = df['unique_words'] / df['word_count']

num_features = ['char_count', 'word_count', 'unique_words', 'lexical_diversity']

for feature in num_features:
    plt.figure(figsize=(10, 6))
    plot_data = df.groupby('status')[feature].mean().sort_values().reset_index()
    sns.barplot(data=plot_data, x='status', y=feature, palette='viridis')
    plt.title(f'Comparison of {feature} across Mental Health Status', fontsize=14)
    plt.xticks(rotation=45)
    plt.show()

corr = df[['word_count','char_count','unique_words','lexical_diversity']].corr()

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

"""Top Words"""

from collections import Counter

def get_top_words(text_series, n=20):
    words = " ".join(text_series).split()
    return Counter(words).most_common(n)

top_words = get_top_words(df['statement'], 20)

words, counts = zip(*top_words)

sns.barplot(x=list(counts), y=list(words))
plt.title("Top Words")
plt.show()

"""# Model 1: LSTM Baseline + RandomUnderSampler

# Install and Import Library
"""

!pip install tensorflow -q
!pip install imbalanced-learn -q

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from imblearn.under_sampling import RandomUnderSampler

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, SpatialDropout1D

print("TensorFlow Version :", tf.__version__)
print("GPU Available      :", len(tf.config.list_physical_devices('GPU')))

"""# Load Dataset and Data Preprocessing"""

df = pd.read_csv('mental_health.csv')

df = df[['statement', 'status']]
df.reset_index(drop=True, inplace=True)

df.dropna(inplace=True)
print(df['status'].value_counts())

"""Data Preprocessing"""

def clean_text_lstm(text):
    # 1. Ubah ke huruf kecil
    text = str(text).lower()

    # 2. Hapus Unicode / Emoji / Karakter Rusak (seperti ðŸ’ª)
    text = text.encode('ascii', 'ignore').decode('ascii')

    # 3. Hapus URL, Mention (@), dan Hashtag (#)
    text = re.sub(r"http\S+", " ", text)
    text = re.sub(r"@\w+", " ", text)
    text = re.sub(r"#\w+", " ", text)

    # 4. Hapus karakter Enter / Newline
    text = re.sub(r"[\n\r]", " ", text)

    # 5. Hapus angka (Angka jarang relevan untuk sentimen mental health)
    text = re.sub(r"\d+", " ", text)

    # 6. Hapus SEMUA tanda baca, sisakan HANYA huruf a-z dan spasi
    text = re.sub(r"[^a-z\s]", " ", text)

    # 7. Rapikan spasi yang berlebihan
    text = re.sub(r"\s+", " ", text).strip()

    return text

df['processed_text'] = df['statement'].apply(clean_text_lstm)

df

"""# Label Encoding"""

label_map = {k:i for i,k in enumerate(df['status'].value_counts().index)}
reverse_label_map = {v: k for k, v in label_map.items()}
num_classes = len(label_map)

df['label'] = df['status'].map(label_map)
print("\nLabel Map:", label_map)

"""# Data Split"""

X_train_raw, X_temp, y_train_raw, y_temp = train_test_split(
    df['processed_text'], df['label'], test_size=0.2, stratify=df['label'], random_state=42
)

X_valid, X_test, y_valid, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42
)

"""# Handle Imbalance (Random Under Sampler)"""

print("\nApplying Random Undersampling on Training Data...")
rus = RandomUnderSampler(random_state=42)

# Reshape X_train_raw untuk imblearn
X_train_resampled, y_train_resampled = rus.fit_resample(
    X_train_raw.values.reshape(-1, 1), y_train_raw
)

# Kembalikan ke format Pandas Series
X_train = pd.Series(X_train_resampled.flatten())
y_train = pd.Series(y_train_resampled)

print("\nDistribusi Train setelah Undersampling:\n", y_train.value_counts())

"""# Tokenization"""

MAX_VOCAB = 10000
MAX_LEN = 64
BATCH_SIZE = 32
EPOCHS = 20

print("\nTokenizing Text Data...")
tokenizer = Tokenizer(num_words=MAX_VOCAB, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = pad_sequences(tokenizer.texts_to_sequences(X_train), maxlen=MAX_LEN, padding='post')
X_valid_seq = pad_sequences(tokenizer.texts_to_sequences(X_valid), maxlen=MAX_LEN, padding='post')
X_test_seq  = pad_sequences(tokenizer.texts_to_sequences(X_test), maxlen=MAX_LEN, padding='post')

"""# Custom Focal Loss Class"""

class SparseCategoricalFocalLoss(tf.keras.losses.Loss):
    def __init__(self, num_classes, gamma=2.0, alpha=0.25, from_logits=False):
        super().__init__()
        self.num_classes = num_classes
        self.gamma = gamma
        self.alpha = alpha
        self.from_logits = from_logits

    def call(self, y_true, y_pred):
        y_true = tf.reshape(tf.cast(y_true, tf.int32), [-1])
        y_true_onehot = tf.one_hot(y_true, depth=self.num_classes)

        if self.from_logits:
            y_pred = tf.nn.softmax(y_pred, axis=-1)

        epsilon = 1e-7
        y_pred = tf.clip_by_value(y_pred, epsilon, 1. - epsilon)

        cross_entropy = -y_true_onehot * tf.math.log(y_pred)
        weight = self.alpha * tf.pow(1 - y_pred, self.gamma)
        loss = weight * cross_entropy

        return tf.reduce_mean(tf.reduce_sum(loss, axis=1))

"""# Model 1: Baseline LSTM + Random Under Sampling"""

print("\nBuilding LSTM Model...")
model_lstm = Sequential([
    Embedding(input_dim=MAX_VOCAB, output_dim=128, input_length=MAX_LEN, mask_zero=True),
    SpatialDropout1D(0.3),
    LSTM(64, dropout=0.2, recurrent_dropout=0.2),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

focal_loss = SparseCategoricalFocalLoss(num_classes=num_classes, gamma=2.0, alpha=0.25, from_logits=False)

model_lstm.compile(optimizer='adam', loss=focal_loss, metrics=['accuracy'])

early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=1, min_lr=1e-6, verbose=1)

"""Training"""

print("\nStarting Training Model 1 (LSTM)...\n")
history_lstm = model_lstm.fit(
    X_train_seq, y_train,
    validation_data=(X_valid_seq, y_valid),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[early_stopping, reduce_lr]
)

"""# Evaluasi Model 1: Baseline LSTM + Random Undersampling"""

print("\nEvaluating Model...\n")
y_pred1_probs = model_lstm.predict(X_test_seq)
y_pred1 = np.argmax(y_pred1_probs, axis=1)

print("\nModel 1 Classification Report:\n")
print(classification_report(y_test, y_pred1, target_names=label_map.keys()))

cm1 = confusion_matrix(y_test, y_pred1)

plt.figure(figsize=(10, 8))
sns.heatmap(
    cm1,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=label_map.keys(),
    yticklabels=label_map.keys()
)

plt.title('Confusion Matrix - Model 1 (LSTM Undersampled)', pad=20, fontsize=14)
plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('Actual Label', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""# Visualisasi Training History"""

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_lstm.history['accuracy'], label='Train Acc')
plt.plot(history_lstm.history['val_accuracy'], label='Val Acc')
plt.title("Model 1 - Accuracy")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_lstm.history['loss'], label='Train Loss')
plt.plot(history_lstm.history['val_loss'], label='Val Loss')
plt.title("Model 1 - Loss")
plt.legend()
plt.show()

"""# Predict Function Model 1 Baseline LSTM + Random Undersampling"""

def predict_model_1(text):
    # 1. Bersihkan teks
    text_processed = clean_text_lstm(text)

    # 2. Ubah teks menjadi angka (Tokenization) dan samakan panjangnya (Padding)
    seq = tokenizer.texts_to_sequences([text_processed])
    pad = pad_sequences(seq, maxlen=MAX_LEN, padding='post')

    # 3. Minta Model 1 untuk menebak
    pred = model_lstm.predict(pad, verbose=0)
    pred_class = np.argmax(pred)
    confidence = np.max(pred)

    # 4. Cetak Hasilnya
    print("Input Text      :", text)
    print("Predicted Label :", reverse_label_map[pred_class])
    print(f"Confidence Score: {confidence:.4f}")
    print("-" * 40)

print("\n--- Uji Coba Prediksi Model 1 ---")
predict_model_1("I feel empty and hopeless everyday")
predict_model_1("Today I am happy and excited")
predict_model_1("I'm constantly worrying about the future and can't breathe")

"""# Model 2 RoBERTa (MentalBERT) + Random Under Sampling

# Install and Environment Setup
"""

!pip uninstall -y transformers -q
!pip install transformers==4.38.2 -q
!pip install tensorflow -q
!pip install imbalanced-learn -q

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from imblearn.under_sampling import RandomUnderSampler

import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

print("TensorFlow Version :", tf.__version__)
print("GPU Available      :", len(tf.config.list_physical_devices('GPU')))

"""# Load Dataset and Data Cleaning"""

df = pd.read_csv("mental_health.csv")
df = df[['statement', 'status']].dropna().reset_index(drop=True)

print("Dataset Shape (Original):", df.shape)

def clean_text_bert(text):
    text = str(text)
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "@USER", text)
    text = text.replace("\n", " ")
    text = text.replace("\r", " ")
    text = text.encode('ascii', 'ignore').decode('ascii')
    text = re.sub(r"\s+", " ", text).strip()

    return text

df['processed_text'] = df['statement'].apply(clean_text_bert)

# Hapus teks yang terlalu pendek (< 4 kata) karena ambigu
df = df[df['processed_text'].str.split().str.len() > 3]
df = df.reset_index(drop=True)

"""# Label Encoding"""

label_map = {label: idx for idx, label in enumerate(df['status'].unique())}
reverse_label_map = {idx: label for label, idx in label_map.items()}
num_classes = len(label_map)

df['label'] = df['status'].map(label_map)

print("\nLabel Mapping:")
print(label_map)

"""# Train Valid Test Split"""

X_train_raw, X_temp, y_train_raw, y_temp = train_test_split(
    df['processed_text'],
    df['label'],
    test_size=0.2,
    stratify=df['label'],
    random_state=42
)

X_valid, X_test, y_valid, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    stratify=y_temp,
    random_state=42
)

"""# Random Undersampling"""

print("\nApplying Random Undersampling on Training Data...")
rus = RandomUnderSampler(random_state=42)

X_train_resampled, y_train_resampled = rus.fit_resample(
    X_train_raw.values.reshape(-1, 1),
    y_train_raw
)

X_train = pd.Series(X_train_resampled.flatten())
y_train = pd.Series(y_train_resampled)

print("\nTrain Size (After Undersampling) :", len(X_train))
print("Valid Size                       :", len(X_valid))
print("Test Size                        :", len(X_test))

"""# Hugging Face"""

!pip install huggingface_hub -q
from huggingface_hub import login

login(token="_____")

"""# Tokenization Mental Bert"""

MODEL_NAME = "mental/mental-bert-base-uncased"
MAX_LEN = 128
BATCH_SIZE = 16
EPOCHS = 4

print(f"\nLoading Tokenizer : {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def encode_data(texts):
    return tokenizer(
        texts.tolist(),
        padding='max_length',
        truncation=True,
        max_length=MAX_LEN,
        return_tensors='tf'
    )

train_encodings = encode_data(X_train)
valid_encodings = encode_data(X_valid)
test_encodings  = encode_data(X_test)

"""# TF Dataset"""

train_dataset = tf.data.Dataset.from_tensor_slices((
    {'input_ids': train_encodings['input_ids'], 'attention_mask': train_encodings['attention_mask']},
    y_train.values
)).shuffle(len(X_train)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

valid_dataset = tf.data.Dataset.from_tensor_slices((
    {'input_ids': valid_encodings['input_ids'], 'attention_mask': valid_encodings['attention_mask']},
    y_valid.values
)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

test_dataset = tf.data.Dataset.from_tensor_slices((
    {'input_ids': test_encodings['input_ids'], 'attention_mask': test_encodings['attention_mask']},
    y_test.values
)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

"""# Build Mental Bert Model"""

print(f"\nLoading Pretrained Model : {MODEL_NAME}")
model = TFAutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=num_classes, from_pt=True)

model.config.hidden_dropout_prob = 0.3
model.config.attention_probs_dropout_prob = 0.3

"""# Custom Focal Loss"""

class SparseCategoricalFocalLoss(tf.keras.losses.Loss):
    def __init__(self, num_classes, gamma=2.0, alpha=0.25, from_logits=False):
        super().__init__()
        self.num_classes = num_classes
        self.gamma = gamma
        self.alpha = alpha
        self.from_logits = from_logits

    def call(self, y_true, y_pred):

        y_true = tf.reshape(tf.cast(y_true, tf.int32), [-1])
        y_true_onehot = tf.one_hot(y_true, depth=self.num_classes)

        if self.from_logits:
            y_pred = tf.nn.softmax(y_pred, axis=-1)

        epsilon = 1e-7
        y_pred = tf.clip_by_value(y_pred, epsilon, 1. - epsilon)

        cross_entropy = -y_true_onehot * tf.math.log(y_pred)

        weight = self.alpha * tf.pow((1 - y_pred), self.gamma)

        loss = weight * cross_entropy

        return tf.reduce_mean(tf.reduce_sum(loss, axis=1))

"""# Compile and Callbacks"""

optimizer = tf.keras.optimizers.Adam(learning_rate=2e-5)

focal_loss = SparseCategoricalFocalLoss(
    num_classes=num_classes,
    gamma=2.0,
    alpha=0.25,
    from_logits=True
)

model.compile(
    optimizer=optimizer,
    loss=focal_loss,
    metrics=['accuracy']
)

early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=1, min_lr=1e-6, verbose=1)

"""# Training"""

print("\nStarting Training...\n")
history = model.fit(
    train_dataset,
    validation_data=valid_dataset,
    epochs=EPOCHS,
    callbacks=[early_stopping, reduce_lr]
)

"""# Evaluation Model 2 Mental Bert"""

print("\nEvaluating Model...\n")
predictions = model.predict(test_dataset)

y_pred_probs = tf.nn.softmax(predictions.logits, axis=-1).numpy()
y_pred = np.argmax(y_pred_probs, axis=1)

y_test_array = y_test.values

weighted_f1 = f1_score(y_test_array, y_pred, average='weighted')
macro_f1 = f1_score(y_test_array, y_pred, average='macro')

print(f"\nWeighted F1 Score : {weighted_f1:.4f}")
print(f"Macro F1 Score    : {macro_f1:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test_array, y_pred, target_names=label_map.keys()))

"""# Training Loss Function"""

cm = confusion_matrix(y_test_array, y_pred)
plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_map.keys(), yticklabels=label_map.keys())
plt.title("Confusion Matrix - MentalBERT (Undersampled)")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.tight_layout()
plt.show()

"""# Prediction Function"""

def predict_mental_health(text):
    cleaned_text = clean_text_bert(text)

    encoded_input = tokenizer(
        cleaned_text, return_tensors='tf', truncation=True, padding='max_length', max_length=MAX_LEN
    )

    outputs = model(encoded_input)
    probs = tf.nn.softmax(outputs.logits, axis=-1).numpy()[0]

    pred_class = np.argmax(probs)
    confidence = probs[pred_class]

    print("Input Text:", text)
    print("\nPredicted Label:", reverse_label_map[pred_class])
    print(f"\nConfidence Score: {confidence:.4f}")
    print("="*50)

print("\n--- TEST PREDICTION ---")
predict_mental_health("I feel hopeless and empty. I don't want to live anymore.")
predict_mental_health("I am very happy today and excited to meet my friends.")
predict_mental_health("My heart is racing and I am terrified to go outside.")

"""# Save Model"""

import os
SAVE_PATH = "./mentalbert_mental_health_model"
os.makedirs(SAVE_PATH, exist_ok=True)

model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print("\nModel & Tokenizer Saved Successfully to:", SAVE_PATH)

"""# Model 1: Baseline LSTM + Smoothed Class Weight

# Install and Environment Setup
"""

!pip install tensorflow -q
!pip install imbalanced-learn -q
import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from sklearn.utils.class_weight import compute_class_weight

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, SpatialDropout1D

print("TensorFlow Version :", tf.__version__)
print("GPU Available      :", len(tf.config.list_physical_devices('GPU')))

"""# Load Dataset and Data Cleaning"""

df = pd.read_csv('mental_health.csv')
df = df[['statement', 'status']]
df.reset_index(drop=True, inplace=True)
df.dropna(inplace=True)

def clean_text_lstm(text):
    text = str(text).lower()
    text = text.encode('ascii', 'ignore').decode('ascii')
    text = re.sub(r"http\S+", " ", text)
    text = re.sub(r"@\w+", " ", text)
    text = re.sub(r"#\w+", " ", text)
    text = re.sub(r"[\n\r]", " ", text)
    text = re.sub(r"\d+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df['processed_text'] = df['statement'].apply(clean_text_lstm)

df = df[df['processed_text'].str.split().str.len() > 3]
df = df.reset_index(drop=True)

"""# Label Encoding"""

label_map = {k:i for i,k in enumerate(df['status'].unique())}
reverse_label_map = {v: k for k, v in label_map.items()}
num_classes = len(label_map)

df['label'] = df['status'].map(label_map)
print("\nLabel Map:", label_map)

"""# Data Split"""

X_train_raw, X_temp, y_train_raw, y_temp = train_test_split(
    df['processed_text'], df['label'], test_size=0.2, stratify=df['label'], random_state=42
)

X_valid_raw, X_test_raw, y_valid_raw, y_test_raw = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42
)

"""# Smoothed Class Weight (Handling Class Imbalance)"""

print("\nCalculating Smoothed Class Weights...")
weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_raw),
    y=y_train_raw
)

class_weights_dict = {k: np.sqrt(v) for k, v in enumerate(weights)}

print("Smoothed Class Weights:")
for k, v in class_weights_dict.items():
    print(f"Class {k} ({reverse_label_map[k]}): {v:.4f}")

"""# Tokenization for Model LSTM"""

MAX_VOCAB = 10000
MAX_LEN = 128
BATCH_SIZE = 32
EPOCHS = 10

print("\nTokenizing Text Data...")
tokenizer = Tokenizer(num_words=MAX_VOCAB, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train_raw)

X_train_seq = pad_sequences(tokenizer.texts_to_sequences(X_train_raw), maxlen=MAX_LEN, padding='post')
X_valid_seq = pad_sequences(tokenizer.texts_to_sequences(X_valid_raw), maxlen=MAX_LEN, padding='post')
X_test_seq  = pad_sequences(tokenizer.texts_to_sequences(X_test_raw), maxlen=MAX_LEN, padding='post')

"""# Custom Focal Loss Class"""

class SparseCategoricalFocalLoss(tf.keras.losses.Loss):
    def __init__(self, num_classes, gamma=2.0, alpha=0.25, from_logits=False):
        super().__init__()
        self.num_classes = num_classes
        self.gamma = gamma
        self.alpha = alpha
        self.from_logits = from_logits

    def call(self, y_true, y_pred):
        y_true = tf.reshape(tf.cast(y_true, tf.int32), [-1])
        y_true_onehot = tf.one_hot(y_true, depth=self.num_classes)

        if self.from_logits:
            y_pred = tf.nn.softmax(y_pred, axis=-1)

        epsilon = 1e-7
        y_pred = tf.clip_by_value(y_pred, epsilon, 1. - epsilon)

        cross_entropy = -y_true_onehot * tf.math.log(y_pred)
        weight = self.alpha * tf.pow(1 - y_pred, self.gamma)
        loss = weight * cross_entropy

        return tf.reduce_mean(tf.reduce_sum(loss, axis=1))

"""# Build LSTM Model"""

print("\nBuilding LSTM Model...")
model_lstm = Sequential([
    Embedding(input_dim=MAX_VOCAB, output_dim=128, input_length=MAX_LEN, mask_zero=True),
    SpatialDropout1D(0.3),
    LSTM(64, dropout=0.2, recurrent_dropout=0.2),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

focal_loss = SparseCategoricalFocalLoss(num_classes=num_classes, gamma=2.0, alpha=0.25, from_logits=False)

model_lstm.compile(optimizer='adam', loss=focal_loss, metrics=['accuracy'])

early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=1, min_lr=1e-6, verbose=1)

"""# Training"""

print("\nStarting Training Model 1 (LSTM)...\n")
history_lstm = model_lstm.fit(
    X_train_seq, y_train_raw,
    validation_data=(X_valid_seq, y_valid_raw),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[early_stopping, reduce_lr],
    class_weight=class_weights_dict
)

"""# Evaluasi Model 1"""

print("\nEvaluating Model...\n")
y_pred1_probs = model_lstm.predict(X_test_seq)
y_pred1 = np.argmax(y_pred1_probs, axis=1)

print("\nModel 1 Classification Report:\n")
print(classification_report(y_test_raw, y_pred1, target_names=label_map.keys()))

cm1 = confusion_matrix(y_test_raw, y_pred1)

plt.figure(figsize=(10, 8))
sns.heatmap(
    cm1,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=label_map.keys(),
    yticklabels=label_map.keys()
)

plt.title('Confusion Matrix - Model 1 (LSTM Smoothed Class Weight)', pad=20, fontsize=14)
plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('Actual Label', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_lstm.history['accuracy'], label='Train Acc')
plt.plot(history_lstm.history['val_accuracy'], label='Val Acc')
plt.title("Model 1 - Accuracy")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_lstm.history['loss'], label='Train Loss')
plt.plot(history_lstm.history['val_loss'], label='Val Loss')
plt.title("Model 1 - Loss")
plt.legend()
plt.show()

"""# Predict Function"""

def predict_model_1(text):
    text_processed = clean_text_lstm(text)
    seq = tokenizer.texts_to_sequences([text_processed])
    pad = pad_sequences(seq, maxlen=MAX_LEN, padding='post')

    pred = model_lstm.predict(pad, verbose=0)
    pred_class = np.argmax(pred)
    confidence = np.max(pred)

    print("\n" + "="*50)
    print("Input Text      :", text)
    print("Predicted Label :", reverse_label_map[pred_class])
    print(f"Confidence Score: {confidence:.4f}")
    print("="*50)

print("\n--- Uji Coba Prediksi Model 1 ---")
predict_model_1("I feel empty and hopeless everyday")
predict_model_1("Today I am happy and excited")
predict_model_1("I'm constantly worrying about the future and can't breathe")

"""# Save Model and ZIP"""

import pickle
import shutil
from google.colab import files

model_lstm.save("model_lstm_smoothed_cw.h5")

with open("tokenizer_lstm_smoothed.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

print("\nModel 1 dan Tokenizer berhasil disimpan!")

SAVE_FOLDER_LSTM = "./lstm_mental_health_model1_final"
os.makedirs(SAVE_FOLDER_LSTM, exist_ok=True)

shutil.move("model_lstm_smoothed_cw.h5", f"{SAVE_FOLDER_LSTM}/model_lstm_smoothed_cw.h5")
shutil.move("tokenizer_lstm_smoothed.pkl", f"{SAVE_FOLDER_LSTM}/tokenizer_lstm_smoothed.pkl")

shutil.make_archive("lstm_mental_health_model1_final", 'zip', SAVE_FOLDER_LSTM)
print("Folder model telah di-zip menjadi lstm_mental_health_model1_final.zip")

files.download("lstm_mental_health_model1_final.zip")

"""# Model 2: MentalBert + Smoothed Class Weight

# Install and Environment Setup
"""

!pip uninstall -y transformers -q
!pip install transformers==4.38.2 -q
!pip install tensorflow -q
!pip install imbalanced-learn -q

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from sklearn.utils.class_weight import compute_class_weight

import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

print("TensorFlow Version :", tf.__version__)
print("GPU Available      :", len(tf.config.list_physical_devices('GPU')))

"""# Load Dataset and Data Cleaning"""

df = pd.read_csv("mental_health.csv")
df = df[['statement', 'status']].dropna().reset_index(drop=True)

print("Dataset Shape (Original):", df.shape)

def clean_text_bert(text):
    text = str(text)
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "@USER", text)
    text = text.replace("\n", " ")
    text = text.replace("\r", " ")
    text = text.encode('ascii', 'ignore').decode('ascii')
    text = re.sub(r"\s+", " ", text).strip()

    return text

df['processed_text'] = df['statement'].apply(clean_text_bert)

# Hapus teks yang terlalu pendek (< 4 kata) karena ambigu
df = df[df['processed_text'].str.split().str.len() > 3]
df = df.reset_index(drop=True)

"""# Label Encoding"""

label_map = {label: idx for idx, label in enumerate(df['status'].unique())}
reverse_label_map = {idx: label for label, idx in label_map.items()}
num_classes = len(label_map)

df['label'] = df['status'].map(label_map)

print("\nLabel Mapping:")
print(label_map)

"""# Train Valid Test Split"""

X_train_raw, X_temp, y_train_raw, y_temp = train_test_split(
    df['processed_text'],
    df['label'],
    test_size=0.2,
    stratify=df['label'],
    random_state=42
)

X_valid_raw, X_test_raw, y_valid_raw, y_test_raw = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    stratify=y_temp,
    random_state=42
)

print("\nTrain Size :", len(X_train_raw))
print("Valid Size :", len(X_valid_raw))
print("Test Size  :", len(X_test_raw))

"""# Smoothed Class Weights"""

print("\nCalculating Smoothed Class Weights...")
weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_raw),
    y=y_train_raw
)

class_weights_dict = {k: np.sqrt(v) for k, v in enumerate(weights)}

print("Smoothed Class Weights Dictionary:")
for k, v in class_weights_dict.items():
    print(f"Class {k} ({reverse_label_map[k]}): {v:.4f}")

"""# Hugging Face Login"""

from huggingface_hub import login

login(token="________")

"""# Tokenization Mental Bert"""

MODEL_NAME = "mental/mental-bert-base-uncased"
MAX_LEN = 256
BATCH_SIZE = 8
EPOCHS = 5

print(f"\nLoading Tokenizer : {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def encode_data(texts):
    return tokenizer(
        texts.tolist(),
        padding='max_length',
        truncation=True,
        max_length=MAX_LEN,
        return_tensors='tf'
    )

train_encodings = encode_data(X_train_raw)
valid_encodings = encode_data(X_valid_raw)
test_encodings  = encode_data(X_test_raw)

"""# TF Dataset"""

train_dataset = tf.data.Dataset.from_tensor_slices((
    {'input_ids': train_encodings['input_ids'], 'attention_mask': train_encodings['attention_mask']},
    y_train_raw.values
)).shuffle(len(X_train_raw)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

valid_dataset = tf.data.Dataset.from_tensor_slices((
    {'input_ids': valid_encodings['input_ids'], 'attention_mask': valid_encodings['attention_mask']},
    y_valid_raw.values
)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

test_dataset = tf.data.Dataset.from_tensor_slices((
    {'input_ids': test_encodings['input_ids'], 'attention_mask': test_encodings['attention_mask']},
    y_test_raw.values
)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

"""# Build Mental Bert Model"""

print(f"\nLoading Pretrained Model : {MODEL_NAME}")
model = TFAutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=num_classes, from_pt=True)

model.config.hidden_dropout_prob = 0.3
model.config.attention_probs_dropout_prob = 0.3

"""# Custom Focal Loss"""

class SparseCategoricalFocalLoss(tf.keras.losses.Loss):
    def __init__(self, num_classes, gamma=2.0, alpha=0.25, from_logits=False):
        super().__init__()
        self.num_classes = num_classes
        self.gamma = gamma
        self.alpha = alpha
        self.from_logits = from_logits

    def call(self, y_true, y_pred):
        y_true = tf.reshape(tf.cast(y_true, tf.int32), [-1])
        y_true_onehot = tf.one_hot(y_true, depth=self.num_classes)

        if self.from_logits:
            y_pred = tf.nn.softmax(y_pred, axis=-1)

        epsilon = 1e-7
        y_pred = tf.clip_by_value(y_pred, epsilon, 1. - epsilon)

        cross_entropy = -y_true_onehot * tf.math.log(y_pred)
        weight = self.alpha * tf.pow(1 - y_pred, self.gamma)
        loss = weight * cross_entropy

        return tf.reduce_mean(tf.reduce_sum(loss, axis=1))

"""# Compile and Callbacks"""

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-5)

focal_loss = SparseCategoricalFocalLoss(num_classes=num_classes, gamma=2.0, alpha=0.25, from_logits=True)

model.compile(optimizer=optimizer, loss=focal_loss, metrics=['accuracy'])

early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=1, min_lr=1e-6, verbose=1)

"""# Training"""

print("\nStarting Training...\n")
history = model.fit(
    train_dataset,
    validation_data=valid_dataset,
    epochs=EPOCHS,
    class_weight=class_weights_dict,
    callbacks=[early_stopping, reduce_lr]
)

"""# Evaluation"""

print("\nEvaluating Model...\n")
predictions = model.predict(test_dataset)

y_pred_probs = tf.nn.softmax(predictions.logits, axis=-1).numpy()
y_pred = np.argmax(y_pred_probs, axis=1)

y_test_array = y_test_raw.values

weighted_f1 = f1_score(y_test_array, y_pred, average='weighted')
macro_f1 = f1_score(y_test_array, y_pred, average='macro')

print(f"\nWeighted F1 Score : {weighted_f1:.4f}")
print(f"Macro F1 Score    : {macro_f1:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test_array, y_pred, target_names=label_map.keys()))

"""# Confusion Matrix and Visualization"""

cm = confusion_matrix(y_test_array, y_pred)
plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_map.keys(), yticklabels=label_map.keys())
plt.title("Confusion Matrix - MentalBERT (Smoothed Class Weight)")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.tight_layout()
plt.show()

"""# Predict Function"""

def predict_mental_health(text):
    cleaned_text = clean_text_bert(text)

    encoded_input = tokenizer(
        cleaned_text, return_tensors='tf', truncation=True, padding='max_length', max_length=MAX_LEN
    )

    outputs = model(encoded_input)
    probs = tf.nn.softmax(outputs.logits, axis=-1).numpy()[0]

    pred_class = np.argmax(probs)
    confidence = probs[pred_class]

    print("\n" + "="*50)
    print("Input Text:", text)
    print("\nPredicted Label:", reverse_label_map[pred_class])
    print(f"\nConfidence Score: {confidence:.4f}")
    print("="*50)

print("\n--- TEST PREDICTION ---")
predict_mental_health("I feel hopeless and empty. I don't want to live anymore.")
predict_mental_health("I am very happy today and excited to meet my friends.")
predict_mental_health("My heart is racing and I am terrified to go outside.")

import os
SAVE_PATH = "./mentalbert_mental_health_model2_final"
os.makedirs(SAVE_PATH, exist_ok=True)

model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print("\nModel & Tokenizer Saved Successfully to:", SAVE_PATH)

import shutil
from google.colab import files

shutil.make_archive("mentalbert_mental_health_model2_final", 'zip', SAVE_PATH)
print("Folder model telah di-zip menjadi mentalbert_saved_model.zip")

files.download("mentalbert_mental_health_model2_final.zip")
