# -*- coding: utf-8 -*-
"""MentalBert Only.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBL1Y33N7RKOe91DXW93Sb2hfpFcKF_u
"""

!pip uninstall -y transformers -q
!pip install transformers==4.38.2 -q
!pip install tensorflow -q

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score

import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

print("TensorFlow Version :", tf.__version__)
print("GPU Available      :", len(tf.config.list_physical_devices('GPU')))

"""# Load Dataset"""

df = pd.read_csv("mental_health.csv")

df = df[['statement', 'status']]
df = df.dropna().reset_index(drop=True)

print("Dataset Shape:", df.shape)
print(df['status'].value_counts())

"""# Text Cleaning"""

def clean_text_bert(text):
    text = str(text)

    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "@USER", text)

    text = text.replace("\n", " ")
    text = text.replace("\r", " ")

    text = text.encode('ascii', 'ignore').decode('ascii')
    text = re.sub(r"\s+", " ", text).strip()

    return text

df['processed_text'] = df['statement'].apply(clean_text_bert)

df = df[df['processed_text'].str.split().str.len() > 3]
df = df.reset_index(drop=True)

print("Dataset Shape After Cleaning:", df.shape)

"""# Label Encoding"""

label_map = {label: idx for idx, label in enumerate(df['status'].unique())}
reverse_label_map = {idx: label for label, idx in label_map.items()}

num_classes = len(label_map)

df['label'] = df['status'].map(label_map)

print("Label Mapping:")
print(label_map)

"""# Train Valid Test Split"""

X_train, X_temp, y_train, y_temp = train_test_split(
    df['processed_text'],
    df['label'],
    test_size=0.2,
    stratify=df['label'],
    random_state=42
)

X_valid, X_test, y_valid, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    stratify=y_temp,
    random_state=42
)

print("Train Size :", len(X_train))
print("Valid Size :", len(X_valid))
print("Test Size  :", len(X_test))

"""# Hugging Face"""

from huggingface_hub import login

login(token="________")

"""# Tokenization Mental Bert"""

MODEL_NAME = "mental/mental-bert-base-uncased"

MAX_LEN = 256
BATCH_SIZE = 8
EPOCHS = 5

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def encode_data(texts):
    return tokenizer(
        texts.tolist(),
        padding='max_length',
        truncation=True,
        max_length=MAX_LEN,
        return_tensors='tf'
    )

train_encodings = encode_data(X_train)
valid_encodings = encode_data(X_valid)
test_encodings  = encode_data(X_test)

"""# TF Dataset"""

train_dataset = tf.data.Dataset.from_tensor_slices((
    {
        'input_ids': train_encodings['input_ids'],
        'attention_mask': train_encodings['attention_mask']
    },
    y_train.values
)).shuffle(len(X_train)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

valid_dataset = tf.data.Dataset.from_tensor_slices((
    {
        'input_ids': valid_encodings['input_ids'],
        'attention_mask': valid_encodings['attention_mask']
    },
    y_valid.values
)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

test_dataset = tf.data.Dataset.from_tensor_slices((
    {
        'input_ids': test_encodings['input_ids'],
        'attention_mask': test_encodings['attention_mask']
    },
    y_test.values
)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

"""# Build Model MentalBERT"""

model = TFAutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=num_classes,
    from_pt=True
)

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-5)

loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

model.compile(
    optimizer=optimizer,
    loss=loss,
    metrics=['accuracy']
)

model.summary()

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=1,
    min_lr=1e-6,
    verbose=1
)

history = model.fit(
    train_dataset,
    validation_data=valid_dataset,
    epochs=EPOCHS,
    callbacks=[early_stopping, reduce_lr]
)

"""# Evaluation"""

predictions = model.predict(test_dataset)

y_pred_probs = tf.nn.softmax(predictions.logits, axis=-1).numpy()
y_pred = np.argmax(y_pred_probs, axis=1)

y_test_array = y_test.values

weighted_f1 = f1_score(y_test_array, y_pred, average='weighted')
macro_f1 = f1_score(y_test_array, y_pred, average='macro')

print(f"Weighted F1 Score : {weighted_f1:.4f}")
print(f"Macro F1 Score    : {macro_f1:.4f}")

print("\nClassification Report (MentalBERT Only):\n")
print(classification_report(
    y_test_array,
    y_pred,
    target_names=label_map.keys()
))

cm = confusion_matrix(y_test_array, y_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=label_map.keys(),
    yticklabels=label_map.keys()
)

plt.title("Confusion Matrix - MentalBERT Only")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""# Training History"""

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title("MentalBERT Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("MentalBERT Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.tight_layout()
plt.show()

"""# Prediction Function"""

def predict_mental_health(text):
    cleaned_text = clean_text_bert(text)

    encoded_input = tokenizer(
        cleaned_text,
        return_tensors='tf',
        truncation=True,
        padding='max_length',
        max_length=MAX_LEN
    )

    outputs = model(encoded_input)
    probs = tf.nn.softmax(outputs.logits, axis=-1).numpy()[0]

    pred_class = np.argmax(probs)
    confidence = probs[pred_class]

    print("=" * 50)
    print("Input Text       :", text)
    print("Predicted Label  :", reverse_label_map[pred_class])
    print(f"Confidence Score : {confidence:.4f}")
    print("=" * 50)

predict_mental_health("I feel hopeless and empty. I don't want to live anymore.")
predict_mental_health("I am very happy today and excited to meet my friends.")
predict_mental_health("My heart is racing and I am terrified to go outside.")

"""# Save Model"""

import os
import shutil
from google.colab import files

SAVE_PATH = "./mentalbert_only"

os.makedirs(SAVE_PATH, exist_ok=True)

model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print("Model & Tokenizer Saved!")

shutil.make_archive(
    "mentalbert_only",
    'zip',
    SAVE_PATH
)

print("ZIP File Created!")

files.download("mentalbert_only.zip")